export const DefaultThemes = {
  widthLayout: {
    MainLayout: '990px',
  },
  fontFamily: {
    BaseFontFamily: 'Roboto Medium',
    BoldBaseFontFamily: 'Roboto Bold',
    LightBaseFontFamily: 'Roboto Light Italic',
    MerriweatherRegularFontSize: 'Merriweather Regular',
    MerriweatherLightFontSize: 'Merriweather Light',
    BuGovFontFamily: 'Times New Roman, Times, serif',
  },
  lineHeight: {
    BaseLineHeight: '22px',
    HeadingH1LineHeight: '43px',
  },
  fontWeight: {
    BaseFontWeight: 'normal',
  },
  fontSize: {
    XXXSmallMobileFontSize: '9px',
    XXSmallMobileFontSize: '10px',
    XSmallMobileFontSize: '11px',
    SmallMobileFontSize: '12px',
    DefaultFonts: '13px',
    MobileFontSize: '14px',
    LargeMobileFontSize: '15px',
    BaseFontSize: '16px',
    MediumFontSize: '17px',
    HeadingH2FontSize: '20px',
    XLargeFontSize: '22px',
    LargeFontSize: '24px',
    HeadingH1FontSize: '36px',
    XXXLargeFontSize: '42px',
  },
  colorStyled: {
    ColorWhite: '#ffffff',
    ColorBlack: '#000000',
    ColorPrimaryBlue: '#385d7e',
    ColorBgList: '#f8f8f8',
    ColorGrey: '#818181',
    ColorMidGrey: '#828282',
    ColorDarkGrey: '#5b5b5b',
    ColorLightGrey: '#585858',
    ColorPrimary: '#434343',
    ColorBgForm: '#ececec',
    ColorSuccess: '#03b079',
    ColorSkipped: '#bdbdbd',
    ColorMing: '#385e7e',
    ColorPeach: '#fee2b4',
    ColorSilver: '#cccccc',
    ColorBorderSilver: '#cbcbcb',
    ColorBorderHampton: '#e3d0ad',
    ColorTimeZoneItemWhite: 'white',
    ColorSilverChalice: '#9e9e9e',
    ColorBgSeashell: '#f1f1f1',
    ColorAlto: '#d6d6d6',
    ColorAlizarinCrimson: '#D92222',
    ColorFunGreen: '#01a41c',
    ColorDoveGray: '#6e6e6e',
  },
};
